### ISSUE TITLE
Something is wrong with the frames

### ISSUE THREAD

**Issue by jonasanx** [mattkersley/Responsive-Design-Testing#10]
When I open it with Google Chrome v19, and I try to watch a website, It just stay loading then in the console, there is a message: "Refused to display document because display forbidden by X-Frame-Options" What is wrong?

**Comment by mattkersley** [comment]
have you changed anything?

I've just checked my own site (which runs the latest version), and it seems to work fine :S

p.s
Sorry for the late reply ;-)

**Comment by jonasanx** [comment]
I found the problem. It fails because Google.com doesn't allow to be embed but then I test my website and It worked. :D

**Comment by mattkersley** [comment]
cool, thanks for the update :)
