### ISSUE TITLE
Feature - Spoofing the UA to fake coming from various devices

### ISSUE THREAD

**Issue by chendrix** [mattkersley/Responsive-Design-Testing#2]
It'd be great to have a separate section that contains spoofed UAs coming from other devices e.g. iPhone at its relevant size, iPad, non-smart-phone, etc.

I've been thinking about how to achieve this, and it could be possible by loading a blank iframe, and using an AJAX request with a spoofed UA to get the relevant page, and then placing it inside of the iframe element.

Only problem is if they click on anything, it would need to continue using AJAXed spoofs to keep the same UA.

**Comment by mattkersley** [comment]
nice idea... that's a bit beyond my skills I'm afraid though.
I'm more of a designer than a developer.

If anyone else wants to give this a bash that would be great :)

**Comment by RyanS** [comment]
So for fun I messed around with this. Most modern browsers do not let you change the user agent of an XHRrequest, it will throw an error. I could set this up via having a small sinatra server do the request for you but it would add a little weight to the repo (ruby, bundler, install instructions).

Might just do it and you can decide if it's worth it or not.

**Comment by mattkersley** [comment]
Hi Ryan.

Sorry for not getting back to you, completely missed this.

After a bit of thinking, I'm not sure it's the best way forward.

Being able to test the site in multiple widths in the browser without a UA being spoofed is great for desktop use as much as devices.

If people are serious enough about testing sites on devices, then they should either buy or borrow one to be sure of it's accuracy.

Thanks for the suggestion though, much appreciated :)
