### ISSUE TITLE
Allow permalinks for specific URLs

### ISSUE THREAD

**Issue by mathiasbynens** [mattkersley/Responsive-Design-Testing#3]
Would be great if we could have permalinks like `http://mattkersley.com/responsive/#http%3A%2F%2Fwww.google.com%2F` or even `http://mattkersley.com/responsive/#google.com` which would then prefill the input and load the given URL.

**Comment by mattkersley** [comment]
Hi Mathias.

You can actually do this already..

http://mattkersley.com/responsive?www.google.com

I will close this and update the readme file at some point.

;-)
